title: Günce Akkoyun
logo: /assets/img/Gunce_Akkoyun.jpg
description: I provide excellent electronics engineering and manufacturing services to industrial clients. I enjoy what I do, take pride in my work, and treat others the way that I want to be treated. I utilize the latest and best technology for both my customers and my own internal processes. These principles have resulted in long-term business relationships and referrals to new clients and colleagues.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal